chore: add dictionary operations
momentohq/client-sdk-go pull request #146
Opened 2023-02-16 21:18 UTC by pgautier404

2023-02-16 23:37 UTC, schwern requested changes

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_fetch.go
> +}
We've gone back and forth about whether we should cache the string versions. My concern is it potentially eats a lot of memory, depends on whether `string(v)` copies the memory or not.

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_fetch.go
> +}
What about byte fields?

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_get_field.go
> +}
Where's the value?

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_get_field.go
> +}
DictionaryGetField doesn't need its own implementation. It can be a thin wrapper around DictionaryGetFields. DictionaryGetField just needs its request and responses and translates.

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
Rather than storing the fields and responses and then building a map in the value methods, could we just build and store a map right here?

The fields and responses are presumably stored so a user can check which fields are a hit and which are a miss, but it's simpler to check if the field exists in the map.

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_increment.go
> +}
Type mismatch. ValueUint32 returns an int64.

The user can see what it returns from the return type, can it be Value()?

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_increment.go
> +	}
Use `ttlMills, refreshTTL := prepareCollectionTtl(r.CollectionTTL, client.defaultTtl)`

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_remove_field.go
> +}
Can be a thin wrapper around DictionaryRemoveFields.

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_set_field.go
> +	})
Can be a thin wrapper around DictionarySetFields.

2023-02-16 23:37 UTC, schwern commented on momento/dictionary_set_fields.go
> +	}
Use prepareCollectionTTL

2023-02-16 23:37 UTC, schwern commented on momento/requester.go
> +}
The check can be extracted into a function that takes Value and returns []byte, error. Something like...

```
func innerPrepareField(f Value) ([]byte, error) {
        field := f.asBytes()

	if len(field) == 0 {
		err := momentoerrors.NewMomentoSvcErr(momentoerrors.InvalidArgumentError, "field cannot be empty", nil)
		return nil, convertMomentoSvcErrorToCustomerError(err)
	}
	return field, nil
}

func prepareField(r hasField) ([]byte, error) {	
	return prepareField(r.field())
}

func prepareFields(r hasFields) ([][]byte, error) {
	var fields [][]byte
	for _, f := range r.fields() {
	    field, err := innerPrepareField(f)
	    if err != nil { return err }
	    fields = append(fields, field)
	}
	return fields, nil
}
```

2023-02-16 23:37 UTC, schwern commented on momento/requester.go
> +func prepareItems(r hasItems) (map[string][]byte, momentoerrors.MomentoSvcErr) {
The function never returns an error. 🤔  I guess that's ok?

2023-02-17 16:51 UTC, pgautier404 commented on momento/dictionary_fetch.go
> +}
Go doesn't allow byte array map keys.

2023-02-17 16:52 UTC, pgautier404 commented on momento/dictionary_get_field.go
> +}
Yeah, thanks, not sure what was going on here. Looks like I meant to come back to this but never did. It's fixed/finished in 2439adce.

2023-02-17 16:54 UTC, pgautier404 commented on momento/dictionary_fetch.go
> +}
Who's we and did you capture the discussion anywhere? I get the memory concerns but also have concerns about performance if these methods are called multiple times. I'm happy to remove the caching code if that's the consensus but would appreciate more context on the discussion.

2023-02-17 16:57 UTC, pgautier404 commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
Responses are not part of a map. They're exposed as their own list as was done in the node SDK. I didn't see that they're used anywhere besides testing but have them here for completeness and consistency.

2023-02-17 17:07 UTC, pgautier404 commented on momento/dictionary_increment.go
> +	}
Exposing `CollectionTtl.ttl` using a `ttl()` method in the requester satisfies `hasScalarTtl()` (which I think could just be called `hasTtl()`). How I have this set up is functionally equivalent to `prepareCollectionTtl` without the need for adding the new method. I think this is a cleaner and DRYer approach and would suggest that we remove `prepareCollectionTtl` and adopt this approach for collection types instead. If we ever need extra specific processing for collection ttls we can add it then. What do you think?

2023-02-17 17:08 UTC, pgautier404 commented on momento/dictionary_set_fields.go
> +	}
See above.

2023-02-17 17:18 UTC, schwern commented on momento/dictionary_fetch.go
> +}
Wat.

2023-02-17 17:29 UTC, schwern commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
tl;dr: I'd say remove responses and fields, the user can do everything with the map value. Once we publish those fields we can't take it back, but we can always add them back later.

I think the responses are an implementation detail that leaked out. It's not in [the SDK docs](https://www.notion.so/momentohq/SDK-API-Methods-Spec-cf12e4db2535405ca2acc3608814b083?pvs=4#74c7425802484341aeca59958f68cb22). Nothing else exposes intermediate responses like that. It doesn't have a purpose that's not fulfilled by the map.

If we make the responses public we have to store all the data twice, once in the responses, once in the items, and a third time for the fields. That's an interface promise, we can't rescind it.

2023-02-17 17:32 UTC, schwern commented on momento/dictionary_increment.go
> +}
We don't do that when there's only one type. See [SDK docs](https://www.notion.so/momentohq/SDK-API-Methods-Spec-cf12e4db2535405ca2acc3608814b083?pvs=4#cbbaaddadb0541bd8a91bbbc4ab313f8).

Also it's warmed over [Hungarian Notation](https://www.notion.so/momentohq/SDK-API-Methods-Spec-cf12e4db2535405ca2acc3608814b083?pvs=4#cbbaaddadb0541bd8a91bbbc4ab313f8). 🤢

2023-02-17 17:39 UTC, schwern commented on momento/dictionary_increment.go
> +	}
tl;dr It's an internal thing, do what you think is best as long as its consistent.

`prepareCollectionTtl` future proofs us against changes to how CollectionTTL is processed, and it reminds us to set the refreshTTL. We can add a hasCollectionTTL.

I'd keep `hasScalarTtl` to disambiguate  between time.Duration TTLs and CollectionTTLs and CollectionTTL.ttl; they're all referred to as "TTL". Maybe `hasDurationTtl`?

2023-02-17 17:50 UTC, schwern requested changes

2023-02-17 17:50 UTC, schwern commented on momento/dictionary_increment.go
> +}
Method name and return type still out of alignment. uint64 vs int64.

It's like those redundant comments that are lies.

```
// Add the thing to the thing.
removeThing(thing)
```

2023-02-17 17:50 UTC, schwern commented on momento/dictionary_get_fields.go
> +	items     []*pb.XDictionaryGetResponse_XDictionaryGetResponsePart
I don't see where `items` is being set.

2023-02-17 17:52 UTC, schwern commented on momento/dictionary_fetch.go
> +}
Just discussions over the course of implementing this in other SDKs. There is no consensus and we haven't done profiling to see if this is a performance concern.

Its a internal issue, so we can change it later. Do what you think is best.

2023-02-17 17:54 UTC, pgautier404 commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
It's in the Node SDK. We already can't rescind it. I'd rather ask the folks who worked on that SDK whether or not there's a reason it's there than just assume it's a mistake. I think there may be value in allowing users to verify that fields missing from the dictionaries returned to them were actually processed.

2023-02-17 17:55 UTC, pgautier404 commented on momento/dictionary_increment.go
> +}
We absolutely do do that in the Node SDK in DictionaryIncrement.

2023-02-17 18:00 UTC, schwern commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
I worked on the Node SDK and I don't know how that slipped in. We can always add it later. We don't need method-for-method parity between SDKs, our customers are unlikely to be using Momento in multiple languages. But we can discuss it in channel.

> I think there may be value in allowing users to verify that fields missing from the dictionaries returned to them were actually processed.

If you're saying they'll want to check if a field was a miss, `_, ok := valueMap[field]`. Simpler and faster and less memory than looping through a list of responses.

2023-02-17 18:28 UTC, pgautier404 commented on momento/dictionary_increment.go
> +	}
I'd rather add special processing for collection ttls when we need to instead of introducing redundant code in anticipation (and all of the list ops already work like this so it's consistent with the approach I was taking before you added the method). I'm just going to continue to reuse `hasScalarTtl()` so I don't have to add a new functionally equivalent interface method to all the existing types. We can easily add a new interface if we ever need to specialize more.

I also added a validation check to `prepareTTL` to make sure we weren't returning values <= 0.

2023-02-17 18:35 UTC, pgautier404 commented on momento/requester.go
> +}
Good callout. I refactored it a bit differently in 7f96990d (added a generalized validator instead of another specialized `prepare` method) and got it DRYed out a bit.

2023-02-17 18:36 UTC, pgautier404 commented on momento/dictionary_increment.go
> +}
Fixed in 7f96990d.

2023-02-17 18:38 UTC, pgautier404 commented on momento/dictionary_get_fields.go
> +	items     []*pb.XDictionaryGetResponse_XDictionaryGetResponsePart
https://github.com/momentohq/client-sdk-go/blob/2439adced0d353f78620d129242bbaa7866aa56c/momento/dictionary_get_fields.go#L120

2023-02-17 18:39 UTC, pgautier404 commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
A miss will not be in valueMap.

2023-02-17 18:52 UTC, pgautier404 commented on momento/requester.go
> +func prepareItems(r hasItems) (map[string][]byte, momentoerrors.MomentoSvcErr) {
Good catch, that should have been validating the keys. Fixed.

2023-02-17 19:18 UTC, schwern commented on momento/dictionary_get_fields.go
> +		r.response = &DictionaryGetFieldsHit{fields: fields, items: rtype.Found.Items, responses: responses}
Do what you think is best.

Chris and Landis and I discussed it in a deveco Slack thread. We didn't come to a consensus.

2023-02-17 19:23 UTC, schwern commented on momento/requester.go
> +func prepareTTL(r hasScalarTTL, defaultTtl time.Duration) (uint64, error) {
Should it be `hasTTL` now?

2023-02-17 20:17 UTC, pgautier404 commented on momento/dictionary_increment.go
> +}
We definitely are copying what the 1.0 SDKs do now, but it's also `Value` in .NET so I'll go along.

2023-02-17 20:39 UTC, schwern approved these changes
lgtm. Thanks for fielding all my feedback.

2023-02-17 20:42 UTC, pgautier404 commented
> lgtm. Thanks for fielding all my feedback.

Totally, thanks for providing it.

2023-02-17 20:43 UTC, merged